config/routes.rb
Rails.application.routes.draw do
  get 'statistiche/stat'
  root "libri#index"

  get 'registrazione', to: 'utenti#new'
  post 'registrazione', to: 'utenti#create'

  get 'richiedi', to: 'prestiti#create'
  delete 'logout', to: 'sessioni#logout'

  get 'login', to: 'sessioni#new'
  post 'login', to: 'sessioni#create'

  get 'approvare', to: 'libri#approvare'
  get 'approva', to: 'libri#approva'

  resources :libri
  resources :prestiti, only: [:show, :index]

  get 'consegna', to: 'prestiti#consegna'
  get 'restituisci', to: 'prestiti#restituisci'
  post 'restituisci', to: 'prestiti#restituzione'

  get 'newisbn', to: "libri#newisbn"
  post 'postisbn', to: "libri#postisbn"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/prestiti_controller.rb
class PrestitiController < ApplicationController
  before_action :qualcuno?
  before_action :admin?, only: [:consegna, :restituisci, :restituzione]

  def create
    unless params[:id]
      redirect_to libri_path
      flash[:warning] = "Non è possibile richiedere un prestito senza specificare quale libro si voglia chiedere in prestito."
    end
    @libro = Libro.find(params[:id].to_i)
    if @mioprestito = Prestito.find_by(utente: utente_corrente, libro: @libro)
      redirect_to @mioprestito
      flash[:danger] = "Non è possibile richiedere un prestito per un libro che si ha già letto. Questa è la pagina del prestito con il quale hai letto questo libro."
    elsif Prestito.find_by(libro: @libro, stato: 0) || Prestito.find_by(libro: @libro, stato: 1)
      redirect_to libri_path
      flash[:danger] = "Ci dispiace ma questo libro è stato già richiesto in prestito da altri."
    elsif utente_corrente.id == @libro.utente.id
      redirect_to libri_path
      flash[:danger] = "Ehi tu! Ma questo è il tuo libro! Non puoi richiedere un prestito per il tuo libro stesso, ce l'hai già a casa!"
    elsif @mioprestito = Prestito.find_by(utente: utente_corrente, stato: 0) || Prestito.find_by(utente: utente_corrente, stato: 1)
      redirect_to @mioprestito
      flash[:danger] = "Non puoi richiedere un prestito per un libro se ne hai già richiesto uno o se non ne hai ancora restituito uno attivo. Questa è la scheda del prestito che hai richiesto e che è nello stato #{statoprestito(@mioprestito)}."
    else
      @prestito = Prestito.new(utente: utente_corrente, libro: @libro, stato: 0)
      if @prestito.save
        redirect_to @prestito
        flash[:success] = "Prestito richiesto con successo."
      else
        redirect_to @prestito
        flash[:danger] = "Errore! #{@prestito.errors.each {|errore| puts errore}}"
      end
    end
  end


  def consegna
    prestito = Prestito.find(params[:id])
    if prestito.stato == 0
      prestito.update(stato: 1, consegna: Date.today, scadenza: Date.today + 15.days)
      redirect_to prestito
      flash[:success] = "La consegna del libro è stata registrata con successo, la data di scadenza è stata inserita."
    else
      redirect_to prestito
      flash[:danger] = "Un prestito consegnato o chiuso non può essere registrato nuovamente come consegnato."
    end
  end

  def restituisci
    @prestito = Prestito.find(params[:id])
    session[:id_prestito] = params[:id]
  end

  def restituzione
    unless session[:id_prestito]
      redirect_to libri_path
      flash[:danger] = "Non è possibile restituire un prestito senza prima aver premuto il tasto di restituzione sul prestito giusto o aver indicato l'ID"
    end
    @prestito = Prestito.find(session[:id_prestito])
    if @prestito.stato == 1
      @prestito.update(recensione: params[:prestito][:recensione], voto: params[:prestito][:ranking], note: params[:prestito][:note], stato: 2, restituzione: Date.today)
      p = Prestito.where(libro_id: @prestito.libro.id)
      @prestito.libro.update_attribute(:voto, p.average(:voto).to_i)
      redirect_to libri_path
      flash[:success] = "Restituzione del libro effettuata con successo"
    else
      redirect_to restituisci_path(id: session[:id_prestito])
      flash[:warning] = "Uno o più parametri non sono stati compilati o non sono stati compilati correttamente."
    end
  end

  def index
    if utente_corrente.admin?
      @utenti = Utente.all
    end
    @prestitiscaduti_usr = Prestito.scadenza.where(utente: utente_corrente)
    @daconsegnare_pers = []
    utente_corrente.libri.each do |libro|
      a = Prestito.where(stato: 0, libro: libro)
      a.each do |pres|
        @daconsegnare_pers.push(pres)
      end
    end
    @pagyuno, @prestiti = pagy(utente_corrente.prestito)
  end

  def show
    @prestito = Prestito.find(params[:id].to_i)
  end

end

app/helpers/prestiti_helper.rb
module PrestitiHelper
  def statoprestito(prestito)
    case prestito.stato
      when 0
        s = 'prestito richiesto'
      when 1
        s = 'libro consegnato'
          if Date.today > prestito.scadenza
            s = 'IN RITARDO SULLA RESTITUZIONE'
          end
      when 2
        s = 'libro restituito'
    end
    return s
  end
end

app/views/prestiti/index.html.erb
<% if utente_corrente.admin? %>
<% if Prestito.scadenza.any? %>
<h1 class="title is-2">Prestiti scaduti</h1>
<% @utenti.each do |utente| %>
  <% @prestitiscaduti = Prestito.scadenza.where(utente: utente)%>
  <% if @prestitiscaduti.any? %>
  <h1 class="subtitle is-4">Prestiti scaduti di <%= utente.cognome.capitalize %> </h1>
  <table class="table">
    <thead>
      <th>Titolo del libro</th>
      <th>Richiedente</th>
      <th>Proprietario</th>
      <th>Consegna</th>
    </thead>
    <tbody>
      <% @prestitiscaduti.each do |prestito| %>
          <tr>
            <td><%= link_to prestito.libro.titolo.capitalize, prestito.libro %></td>
            <td><%= prestito.utente.cognome.capitalize %></td>
            <td><%= prestito.libro.utente.cognome.capitalize %></td>
            <td><%= link_to 'Restituisci prestito', restituisci_path(:id => prestito.id), class: 'button is-danger is-medium'%></td>
          </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
  <% end %>
<% end %>
<% if !utente_corrente.admin? && @prestitiscaduti_usr.any? %>
<h1 class="title is-2">Prestiti scaduti</h1>
<h1 class="subtitle is-4">Ricordati di restituire il libro a scuola nel primo giorno utile.</h1>
<table class="table">
  <thead>
    <th>Titolo del libro</th>
    <th>Proprietario</th>
  </thead>
  <tbody>
    <% @prestitiscaduti_usr.each do |prestito| %>
        <tr>
          <td><%= link_to prestito.libro.titolo.capitalize, prestito.libro %></td>
          <td><%= prestito.libro.utente.cognome.capitalize %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<% end %>
<% if utente_corrente.admin? %>
<% if Prestito.where(stato: 0).any? %>
<h1 class="title is-2">Prestiti da consegnare</h1>
<% @utenti.each do |utente| %>
<% @daconsegnare_all = Prestito.where(stato: 0, utente: utente)%>
<% if @daconsegnare_all.any? %>
<h1 class="subtitle is-4">Prestiti da consegnare a <%= utente.cognome.capitalize %> </h1>
<table class="table">
  <thead>
    <th>Titolo del libro</th>
    <th>Proprietario</th>
    <th>Consegna</th>
  </thead>
  <tbody>
    <% @daconsegnare_all.each do |prestito| %>
      <tr>
        <td><%= link_to prestito.libro.titolo.capitalize, prestito.libro %></td>
        <td><%= prestito.libro.utente.cognome.capitalize %></td>
        <td><%= link_to 'Consegna prestito', consegna_path(:id => prestito.id), class: 'button is-warning is-medium'%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<% end %>
<% end %>

<% elsif @daconsegnare_pers.any? && !utente_corrente.admin? %>
<h1 class="title is-1">Libri da consegnare in prestito</h1>
<p>Porta il libro a scuola domani e consegnalo a chi si occupa della biblioteca. Assicurati che si ricordi di inserire il prestito a sistema dal suo account amministratore.</p>
<table class="table">
  <thead>
    <th>Titolo del libro</th>
    <th>Proprietario</th>
  </thead>
  <tbody>
    <% @daconsegnare_pers.each do |prestito| %>
      <tr>
        <td><%= link_to prestito.libro.titolo.capitalize, prestito.libro %></td>
        <td><%= prestito.utente.cognome.capitalize %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>


<h1 class="title is-3">Storico generale prestiti </h1><button  id="mostratutti" class="button is-primary is-medium">Mostra tutti</button>

<div id="storico"></div>

<script>
$('#mostratutti').click(function(){
  $("#storico").append('<% if !utente_corrente.admin?%> <table class="table"><thead><th>Titolo del libro</th><th>Scadenza</th><th>Stato</th><th>Pagina</th>  </thead><tbody><% @prestiti.each do |prestito| %><tr>  <td><%= prestito.libro.titolo.capitalize %></td><td><%= prestito.scadenza.strftime("%d/%m/%y") if !prestito.scadenza.nil? %> </td><td><%= statoprestito(prestito) %> </td>  <td><%= link_to "Pagina prestito", prestito, class: "button is-info is-small" %></td>  </tr>  <% end %>  </tbody> </table> <% end %> <% if utente_corrente.admin? %>  <% @utenti.each do |utente| %> <% if utente.prestito.any? %><h1 class="subtitle is-4">Richiesti da <%= utente.cognome.capitalize %></h1> <table class="table"> <thead>  <th>Titolo del libro</th> <th>Scadenza</th>  <th>Stato</th>  <th>Pagina</th></thead><tbody>  <% utente.prestito.each do |prestito| %>  <tr> <td><%= prestito.libro.titolo.capitalize %></td><td><%= prestito.scadenza.strftime("%d/%m/%y") if !prestito.scadenza.nil?%> </td><td><%= statoprestito(prestito) %> </td><td><%= link_to "Pagina prestito", prestito, class: "button is-info is-small" %></td></tr> <% end %>  </tbody></table><% end %><% end %><% end %>');
  $('#mostratutti').addClass('is-hidden');
});
</script>

app/views/prestiti/restituisci.html.erb
<h1 class="title is-1">Scheda di restituzione per il prestito <%= @prestito.id %> del libro <%= @prestito.libro.titolo.capitalize %></h1>
<%= form_for(@prestito, url: restituisci_path, method: :post, :html => { :class => 'rating' } ) do |f| %>

  <div class="control">
    <%= f.label :recensione, class: 'label' %>
    <%= f.text_area :recensione, class: 'textarea' %>
  </div>

  <label class="label" for="libro-valutazione">Valuta il libro</label>
  <fieldset class="starability-basic" id="libro-valutazione">
  <input type="radio" id="first-rate1" name="prestito[ranking]" value="1" />
  <label for="first-rate1" title="Terribile">1 stella</label>
  <input type="radio" id="first-rate2" name="prestito[ranking]" value="2" />
  <label for="first-rate2" title="Per niente buono">2 stelle</label>
  <input type="radio" id="first-rate3" name="prestito[ranking]" value="3" />
  <label for="first-rate3" title="Nella media">3 stelle</label>
  <input type="radio" id="first-rate4" name="prestito[ranking]" value="4" />
  <label for="first-rate4" title="Molto buono">4 stelle</label>
  <input type="radio" id="first-rate5" name="prestito[ranking]" value="5" />
  <label for="first-rate5" title="Buonissimo">5 stelle</label>
  </fieldset>

  <div class="control">
    <%= f.label 'Note sullo stato del libro', class: 'label' %>
    <%= f.text_area :note, class: 'textarea' %>
  </div>

<br />
<%= f.submit 'Salva dati e conferma restituzione', class: 'button is-danger is-medium' %>
<% end %>

app/views/prestiti/show.html.erb
<h1 class="title is-2">Prestito <%= @prestito.id %> per il libro <%= link_to @prestito.libro.titolo.capitalize, @prestito.libro %></h1>
<h2 class="subtitle is-2">Stato: <%= statoprestito(@prestito) %></h2>
<h2 class="subtitle is-4">Proprietario del libro: <%= @prestito.libro.utente.cognome.capitalize %></h2>
<h2 class="subtitle is-4">Richiedente del prestito: <%= @prestito.utente.cognome.capitalize %></h2>
<% if @prestito.stato >= 1 %>
  <h2 class="subtitle is-4">Consegna effettuata: <%= @prestito.consegna.strftime('%d/%m/%y') %></h2>
  <h2 class="subtitle is-4">Scadenza del prestito: <%= @prestito.scadenza.strftime('%d/%m/%y') %></h2>
<% end %>
<% if @prestito.stato == 1 && utente_corrente.admin? %>
  <%= link_to 'Restituisci prestito', restituisci_path(id: @prestito.id), class: 'button is-link is-large'%>
<% end %>
<% if @prestito.stato == 2 %>
  <h2 class="subtitle is-4">Libro restituito: <%= @prestito.restituzione.strftime('%d/%m/%y') %></h2>
<% end %>
<% if @prestito.recensione %>
  <h2 class="title is-4">Recensione con voto <%= @prestito.voto %></h2>
  <p><%= @prestito.recensione %></p>
<% end %>