config/routes.rb
Rails.application.routes.draw do
  get 'statistiche/stat'
  root "libri#index"

  get 'registrazione', to: 'utenti#new'
  post 'registrazione', to: 'utenti#create'

  get 'richiedi', to: 'prestiti#create'
  delete 'logout', to: 'sessioni#logout'

  get 'login', to: 'sessioni#new'
  post 'login', to: 'sessioni#create'

  get 'approvare', to: 'libri#approvare'
  get 'approva', to: 'libri#approva'

  resources :libri
  resources :prestiti, only: [:show, :index]

  get 'consegna', to: 'prestiti#consegna'
  get 'restituisci', to: 'prestiti#restituisci'
  post 'restituisci', to: 'prestiti#restituzione'

  get 'newisbn', to: "libri#newisbn"
  post 'postisbn', to: "libri#postisbn"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/libri_controller.rb
class LibriController < ApplicationController
  before_action :qualcuno?
  before_action :admin?, only: [:approva, :approvare]

  def new
    if(params[:isbn].blank?)
      @libro = Libro.new
    else
      @libro = Libro.new(titolo: params[:titolo], autore: params[:autore], editore: params[:editore], isbn: params[:isbn], anno: params[:anno].to_i)
    end
  end

  def newisbn
  end

  def postisbn
    url = "http://opac.sbn.it/opacmobilegw/search.json?isbn=" + params[:isbn]
    data = HTTParty.get(url).to_h
    # risposta di esempio 
    # => {"numFound"=>1, "start"=>0, "rows"=>20, "briefRecords"=>[{"progressivoId"=>0, "codiceIdentificativo"=>"IT\\ICCU\\UBO\\4283020", "isbn"=>"978-88-08-52068-5", "autorePrincipale"=>"Carrada, Luisa", "copertina"=>"http://covers.librarything.com/devkey/fd11eebee79ccfcfe2f17d34a92e1011/small/isbn/9788808520685", "titolo"=>"Guida di stile : scrivere e riscrivere con consapevolezza / Luisa Carrada", "pubblicazione"=>"Bologna : Zanichelli, 2017", "livello"=>"Monografia", "tipo"=>"Testo a stampa", "numeri"=>[], "note"=>[], "sommarioAbstract"=>[], "nomi"=>[], "luogoNormalizzato"=>[], "localizzazioni"=>[], "citazioni"=>[]}], "facetRecords"=>[{"facetName"=>"level", "facetLabel"=>"Livello bibliografico", "facetValues"=>[["Monografia", "m", "1"]]}, {"facetName"=>"tiporec", "facetLabel"=>"Tipo di documento", "facetValues"=>[["Testo a stampa", "a", "1"]]}, {"facetName"=>"nomef", "facetLabel"=>"Autore", "facetValues"=>[["carrada, luisa", "carrada, luisa", "1"]]}, {"facetName"=>"soggettof", "facetLabel"=>"Soggetto", "facetValues"=>[["redazione di testi", "redazione di testi", "1"]]}, {"facetName"=>"luogof", "facetLabel"=>"Luogo di pubblicazione", "facetValues"=>[["bologna", "bologna", "1"]]}, {"facetName"=>"lingua", "facetLabel"=>"Lingua", "facetValues"=>[["italiano", "ita", "1"]]}, {"facetName"=>"paese", "facetLabel"=>"Paese", "facetValues"=>[["italia", "it", "1"]]}]}
    if data["numFound"] > 0
      book = data["briefRecords"].first
      autore_from = book["autorePrincipale"].gsub(/<[\d\-\s]*>+/, "").split(",")
      autore = "#{autore_from[1].strip} #{autore_from[0].strip}"
      pubblicazione = book["pubblicazione"].match(/([\w\s]*):\s*([\w*\s*\-*\s*]*)\s*,*\s*(\d*)/i)
      editore = pubblicazione[2].strip
      anno = pubblicazione[3].strip
      redirect_to new_libro_path(titolo: book["titolo"].split("/")[0].strip, autore: autore, editore: editore, isbn: params[:isbn].gsub("-", "").strip, anno: anno)
    else
      flash[:warning] = "Nessun libro trovato sul Catalogo del Servizio Bibliotecario Nazionale (OPAC SBN) con questo ISBN"
      redirect_to newisbn_path
    end

  end

  def create
    if utente_corrente.admin?
      stato = 1
      findutente = Utente.find_by_cognome(params[:libro][:utente].downcase)
      if findutente
        utente = findutente
      else
        utente = utente_corrente
      end
    else
      utente = utente_corrente
      stato = 0
    end
      @libro = Libro.new(parametri_creazione.merge(utente: utente, stato: stato))
    if @libro.save
      redirect_to @libro
      flash[:success] = "Grazie per aver deciso di condividere questo libro con la classe, #{utente_corrente.cognome.capitalize}"
    else
      redirect_to new_libro_path
      flash[:danger] = "#{@libro.errors.each {|errore| puts errore.to_s }}"
    end
  end

  def index
    unless loggato?
      redirect_to login_path
    end
    @ricerca = Libro.search(params[:cerca], params[:genere], params[:pagine])
      if params[:disponibili].nil?
        @pagy, @libro = pagy(@ricerca)
      elsif params[:disponibili] == '1'
        @librivalidi = []
        @ricerca.each do |libro|
          if !Prestito.where(libro: libro, stato: 1).or(Prestito.where(libro: libro, stato: 0))  .any?
            @librivalidi.push(libro)
          end
        end
        @pagy, @libro = pagy(Libro.where(id: @librivalidi.map(&:id)))
      end
  end

  def show
    @libro = Libro.find(params[:id].to_i)
  end

  def approvare
    @libri = Libro.where(stato: 0)
  end

  def approva
    @libro = Libro.find(params[:id].to_i)
    if utente_corrente.admin?
      @libro.update_attribute(:stato, 1)
      redirect_to root_path
      flash[:success] = 'Libro approvato'
    else
      redirect_to root_path
      flash[:danger] = "Non sei amministratore. Tornatene da dove sei venuto."
    end
  end

  def edit
    @libro = Libro.find(params[:id])
    unless utente_corrente.admin? || @libro.utente == utente_corrente
      redirect_to libri_path
      flash[:danger] = 'Non sei admin o il proprietario del libro. Tornatene da dove sei venuto.'
    end
    session[:libro_modifica] = @libro.id
  end

  def destroy
    @libro = Libro.find(params[:id])
    unless utente_corrente.admin? || @libro.utente == utente_corrente
      redirect_to libri_path and return
      flash[:danger] = 'Non sei admin o il proprietario del libro. Tornatene da dove sei venuto.'
    end
      if @libro.destroy
        redirect_to root_path
        flash[:success] = "Libro eliminato con successo."
      end
  end

  def update
    @libro = Libro.find(session[:libro_modifica]) || Libro.find(params[:id])
    unless utente_corrente.admin? || @libro.utente == utente_corrente
      redirect_to libri_path and return
      flash[:danger] = 'Non sei admin o il proprietario del libro. Tornatene da dove sei venuto.'
    end
      if !params[:libro][:utente].blank?
        utente = Utente.find_by_cognome(params[:libro][:utente].downcase)
      else
        utente = @libro.utente
      end
      if @libro.update(parametri_creazione.merge(utente: utente))
        redirect_to @libro
        flash[:success] = "Informazioni del libro modificate con successo."
      else
        render 'edit'
        flash[:danger] = "Errore #{@libro.errors.each { |error| puts error}}"
      end
  end

end

private
  def parametri_creazione
      params.require(:libro).permit(:titolo, :autore, :utente, :isbn, :trama, :foto, :costo, :immagine, :genere, :pagine, :editore, :anno)
  end

app/helpers/libri_helper.rb
module LibriHelper
end

app/views/libri/approvare.html.erb
<h1 class="title is-1">Libri da approvare</h1>
<% if @libri.nil? %>
<h1 class="title is-1" style="text-align:center;">Nessun prestito da approvare</h1>
<% else %>
<table class="table">
  <thead>
    <th>Titolo</th>
    <th>Trama</th>
    <th>Approva</th>
    <th>Modifica o cancella</th>
  </thead>
  <tbody>
    <% @libri.each do |libro| %>
      <tr>
        <td><%= link_to libro.titolo.capitalize, libro %></td>
        <td><%= libro.trama %></td>
        <td><%= link_to 'Appova', approva_path(:id => libro.id), class: 'button is-primary is-small', data: {confirm: 'Questo libro verrà reso immediatamente disponibile per il prestito.'}%></td>
        <td><%= link_to 'Modifica', edit_libro_path(libro.id), class: 'button is-small is-warning'%>  <%= link_to 'Elimina', libro_path(libro.id), class: 'button is-danger is-small', method: :delete, data: {confirm: 'Sei davvero sicuro di voler eliminare questo libro? Il titolo sarà CANCELLATO dal programma così come eventualmente i log. Sii davvero sicuro di quello che fai.'}%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/libri/edit.html.erb
<h1 class="title is-2">Modifica libro: <%= @libro.titolo %></h1>
<%= form_for(@libro, url: libro_path(@libro.id), method: :patch) do |f| %>
  <div class="control">
    <%= f.label :titolo, class: 'label' %>
    <%= f.text_field :titolo, class: 'input' %>
  </div>
  <div class="control">
    <%= f.label :autore, class: 'label' %>
    <%= f.text_field :autore, class: 'input' %>
  </div>
  <div class="control">
    <%= f.label :editore, class: 'label' %>
    <%= f.text_field :editore, class: 'input' %>
  </div>
  <div class="control">
    <%= f.label :anno, class: 'label' %>
    <%= f.number_field :anno, max: Date.today.year, min: 1600, class: 'input' %>
  </div>
  <div class="control">
    <%= f.label :isbn, class: 'label' %>
    <%= f.text_field :isbn, class: 'input' %>
  </div>
    <%= f.label :trama, class: 'label' %>
    <%= f.text_area :trama, class: 'textarea' %>
  <div class="control">
    <%= f.label 'Quanto lo pagheresti in libreria?', class: 'label' %>
    <%= f.number_field :costo, step: 0.01, class: 'input' %>
  </div>

  <% generi = ["N/A", "Storico", "fantascienza", "fantasy", "avventura", "horror", "azione", "thriller", "giallo", "rosa", "umoristico", "fiaba", "biografia", "diario", "divulgativo-argomentativo", "poesia"]  %>
  <div class="select">
    <%= f.label :genere, class: 'label' %>
    <%= f.select :genere, generi %>
  </div>
  <% pagine = ["N/A", "0-100", "100-200", "200-300", "300+"]  %>
  <div class="select">
    <%= f.label :pagine, class: 'label' %>
    <%= f.select :pagine, pagine %>
  </div>
  <script>
  // direct_uploads.js

addEventListener("direct-upload:initialize", event => {
  const { target, detail } = event
  const { id, file } = detail
  target.insertAdjacentHTML("beforebegin", `
    <div id="direct-upload-${id}" class="direct-upload direct-upload--pending">
      <div id="direct-upload-progress-${id}" class="direct-upload__progress" style="width: 0%"></div>
      <span class="direct-upload__filename">${file.name}</span>
    </div>
  `)
})

addEventListener("direct-upload:start", event => {
  const { id } = event.detail
  const element = document.getElementById(`direct-upload-${id}`)
  element.classList.remove("direct-upload--pending")
})

addEventListener("direct-upload:progress", event => {
  const { id, progress } = event.detail
  const progressElement = document.getElementById(`direct-upload-progress-${id}`)
  progressElement.style.width = `${progress}%`
})

addEventListener("direct-upload:error", event => {
  event.preventDefault()
  const { id, error } = event.detail
  const element = document.getElementById(`direct-upload-${id}`)
  element.classList.add("direct-upload--error")
  element.setAttribute("title", error)
})

addEventListener("direct-upload:end", event => {
  const { id } = event.detail
  const element = document.getElementById(`direct-upload-${id}`)
  element.classList.add("direct-upload--complete")
})
</script>
<br />
<br />
<br />
<label class="label" >Foto della copertina</label>
<%= f.file_field :immagine, multiple: false, direct_upload: true %>

  <% if utente_corrente.admin? %>
    <div class="control">
      <%= f.label "Cognome dell'utente (scrivere solo se da modificare)", class: 'label' %>
      <input type="text" class="input" name="libro[utente]" />
    </div>
  <% end %>
  <br />
  <%= f.submit 'Modifica', class: 'button is-primary' %>
<% end %>

app/views/libri/index.html.erb
<h1 class="title is-2">Elenco dei libri</h1>
<%= link_to 'Aggiungi nuovo libro', new_libro_path, class: 'button is-primary' %>
<%= link_to 'Nuovo libro da ISBN', newisbn_path, class: 'button is-info is-small' %>
<br />
<br />
<div class="is-horizontal">

<form action="/" method="get">
<div class="field has-addons">
  <div class="control">
     <input class="input" placeholder="Titolo o autore" name="cerca" id="cerca-libro-field"/>
  </div>
  <div class="control">
    <input type="submit" class="button is-info" label="Cerca" onclick="empty()"/>
  </div>
</div>

<b>Filtri per la ricerca</b> <p style="font-size: 8px;">Suggerimento: puoi anche evitare di specificare un titolo ed effettuare una ricerca per generi o pagine!</p>
<div class="level level-left">
<label for="select-generi" class="label">Genere</label>
<br />
<br />
<div class="select" id="select-generi">
<select name="genere">
  <option></option>
  <option>Storico</option>
  <option>fantascienza</option>
  <option>fantasy</option>
  <option>avventura</option>
  <option>horror</option>
  <option>azione</option>
  <option>thriller</option>
  <option>giallo</option>
  <option>rosa</option>
  <option>umoristico</option>
  <option>fiaba</option>
  <option>biografia</option>
  <option>diario</option>
  <option>divulgativo-argomentativo</option>
  <option>poesia</option>
</select>
</div>
<br />
<label for="select-pagine" class="label">Pagine</label>
<br />
<div class="select" id="select-pagine">
<select name="pagine">
  <option></option>
  <option>0-100</option>
  <option>100-200</option>
  <option>200-300</option>
  <option>300+</option>
</select>
</div>
</div>
</form>
<!-- FINE FORM DI RICERCA -->

<% if @libro.nil? %>
<h1 class="title is-2 has-text-centered">La ricerca non ha trovato nessun libro</h1>
<% else %>
<table class="table">
  <thead>
    <tr>
      <th><i class="fas fa-image"></i></th>
      <th>Titolo</th>
      <th>Autore</th>
      <th>Gen. e pag.</th>
      <th>Richiedi</th>
    </th>
  </thead>
  <tbody>
    <% @libro.each do |libro| %>
      <tr>
        <% if libro.immagine.attached? %>
          <td><%= image_tag libro.immagine.variant(resize: '100') %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to libro.titolo.capitalize, libro %></td>
        <td><%= libro.autore.capitalize %></td>
        <td><%= libro.genere %><br /><%= libro.pagine %></td>
        <td><%= link_to 'Richiedi in prestito', richiedi_path(:id => libro.id), class: 'button is-primary is-medium', data: {confirm: "Vuoi richiedere il libro #{libro.titolo.capitalize.strip} in prestito?" }%> <%= link_to 'Scheda del libro', libro, class: 'button is-info is-small'%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<%== pagy_bulma_nav_js(@pagy) if @pagy.pages > 1 %>

app/views/libri/new.html.erb
<h1 class="title is-2">Aggiungi libro</h1>
<p>Da qui potrai aggiungere un libro che vuoi offrire in prestito alla classe.</p>
<%= form_for(@libro, url: libri_path, method: :post) do |f| %>
  <div class="control">
    <%= f.label :titolo, class: 'label' %>
    <%= f.text_field :titolo, class: 'input' %>
  </div>
  <div class="control">
    <%= f.label :autore, class: 'label' %>
    <%= f.text_field :autore, class: 'input' %>
  </div>
  <div class="control">
    <%= f.label :editore, class: 'label' %>
    <%= f.text_field :editore, class: 'input' %>
  </div>
  <div class="control">
    <%= f.label :anno, class: 'label' %>
    <%= f.number_field :anno, max: Date.today.year, min: 1600, class: 'input' %>
  </div>
  <div class="control">
    <%= f.label :isbn, class: 'label' %>
    <%= f.text_field :isbn, class: 'input' %>
  </div>
    <%= f.label :trama, class: 'label' %>
    <%= f.text_area :trama, class: 'textarea' %>
  <div class="control">
    <%= f.label 'Quanto lo pagheresti in libreria?', class: 'label' %>
    <%= f.number_field :costo, step: 0.01, class: 'input' %>
  </div>

  <% generi = ["N/A", "Storico", "fantascienza", "fantasy", "avventura", "horror", "azione", "thriller", "giallo", "rosa", "umoristico", "fiaba", "biografia", "diario", "divulgativo-argomentativo", "poesia"]  %>
  <div class="select">
    <%= f.label :genere, class: 'label' %>
    <%= f.select :genere, generi %>
  </div>
  <% pagine = ["N/A", "0-100", "100-200", "200-300", "300+"]  %>
  <div class="select">
    <%= f.label :pagine, class: 'label' %>
    <%= f.select :pagine, pagine %>
  </div>
  
  <script>
  // direct_uploads.js

addEventListener("direct-upload:initialize", event => {
  const { target, detail } = event
  const { id, file } = detail
  target.insertAdjacentHTML("beforebegin", `
    <div id="direct-upload-${id}" class="direct-upload direct-upload--pending">
      <div id="direct-upload-progress-${id}" class="direct-upload__progress" style="width: 0%"></div>
      <span class="direct-upload__filename">${file.name}</span>
    </div>
  `)
})

addEventListener("direct-upload:start", event => {
  const { id } = event.detail
  const element = document.getElementById(`direct-upload-${id}`)
  element.classList.remove("direct-upload--pending")
})

addEventListener("direct-upload:progress", event => {
  const { id, progress } = event.detail
  const progressElement = document.getElementById(`direct-upload-progress-${id}`)
  progressElement.style.width = `${progress}%`
})

addEventListener("direct-upload:error", event => {
  event.preventDefault()
  const { id, error } = event.detail
  const element = document.getElementById(`direct-upload-${id}`)
  element.classList.add("direct-upload--error")
  element.setAttribute("title", error)
})

addEventListener("direct-upload:end", event => {
  const { id } = event.detail
  const element = document.getElementById(`direct-upload-${id}`)
  element.classList.add("direct-upload--complete")
})
</script>
<br />
<br />
<br />
<label class="label" >Foto della copertina</label>
<%= f.file_field :immagine, multiple: false, direct_upload: true %>

  <% if utente_corrente.admin? %>
    <div class="control">
      <%= f.label "Cognome dell'utente", class: 'label' %>
      <%= f.text_field :utente, class: 'input' %>
    </div>
  <% end %>
  <br />
  <%= f.submit 'Aggiungi libro', class: 'button is-primary' %>
<% end %>

app/views/libri/newisbn.html.erb
<%= form_with(url: postisbn_path) do |f| %>
  <div class="control">
    <%= f.label :isbn, class: 'label' %>
    <%= f.text_field :isbn, class: 'input' %>
  </div>
  
  <%= f.submit 'Aggiungi libro', class: 'button is-primary' %>
<% end %>

app/views/libri/show.html.erb
<%= image_tag @libro.immagine.variant(resize: "500"), align: :right if @libro.immagine.attached? %>
<h1 class="title is-2"><%= @libro.titolo.capitalize %></h1>
<h2 class="subtitle is-3"><b>Autore: </b><%= @libro.autore.capitalize %></h2>
<h2 class="subtitle is-4"><b>Editore: </b><%= @libro.editore.capitalize %></h2>
<p><b>Genere:</b> <%= @libro.genere.capitalize %></p>
<p><b>Pagine:</b> <%= @libro.pagine %></p>
<p><b>Proprietario:</b> <%= @libro.utente.cognome.capitalize %></p>
<% if utente_corrente.admin? || @libro.utente == utente_corrente %>
<br />
  <%= link_to 'Modifica', edit_libro_path(@libro.id), class: 'button is-warning is-small' %>
  <%= link_to 'Elimina', libro_path(@libro.id), class: 'button is-danger is-small', method: :delete, data: {confirm: 'Sei davvero sicuro di voler eliminare questo libro? Il libro sarà CANCELLATO dal programma così come eventualmente i log. Sii davvero sicuro di quello che fai.'} %>
  <br />
<% end %>
  <br />
<% if @libro.stato == 1 %>
  <%= link_to 'Richiedi in prestito', richiedi_path(:id => @libro.id), class: 'button is-primary is-large', data: {confirm: "Vuoi richiedere il libro #{@libro.titolo.capitalize.strip} in prestito?" }%>
<% end %>
<br />
<br />
<% if !@libro.trama.blank? %>
  <h2 class="title is-3">Trama</h2>
<p><%= @libro.trama %></p>
<br />
<% end %>
<% if !@libro.costo.blank? %>
  <p>Se lo prendessi in libreria, pagheresti questo libro <%= number_to_currency(@libro.costo, unit: "€", separator: ',', delimiter: '.', raise: false, format: '%u %n')%>.</p>
  <br />
<% end %>
<% if !@libro.voto.blank? %>
  <p>La media dei voti di questo libro è di <b><%= @libro.voto %></b>.</p>
  <br />
<% end %>
<% if @libro.prestito.any? %>
  <h1 class="title is-3">Storico prestiti</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Richiedente</th>
        <th>Recensione</th>
        <th>Pagina prestito</th>
        <th>Stato</th>
      </tr>
    </thead>
    <tbody>
      <% @libro.prestito.each do |prestito| %>
        <tr>
          <td><%= prestito.utente.cognome.capitalize %></td>
          <td><%= prestito.recensione %></td>
          <td><%= link_to 'Scheda prestito', prestito, class: 'button is-info' %></td>
          <td><%= statoprestito(prestito) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>